# Generated by Django 3.2.6 on 2021-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('identifier', models.IntegerField()),
                ('role', models.CharField(choices=[('MANAGER', 'Manager'), ('LEADER', 'Leader'), ('USER', 'User')], default='USER', max_length=20)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
