# Generated by Django 3.2.6 on 2021-08-03 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.project'),
        ),
    ]
