# Generated by Django 3.2.6 on 2021-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_user_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
