# Generated by Django 3.2.6 on 2021-08-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_auto_20210804_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TEAM_LEADER', 'Team Leader'), ('TEAM_MEMBER', 'Team Member')], default='TEAM_MEMBER', max_length=20),
        ),
    ]
