# Generated by Django 3.2.6 on 2021-08-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
