# Generated by Django 3.2.6 on 2021-08-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_user_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
