# Generated by Django 3.2.6 on 2021-08-04 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools', '0004_auto_20210804_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('VALIDATED', 'Validated'), ('POSTPONED', 'Postponed'), ('REJECTED', 'Rejected')], default=('IN_PROGRESS', 'In progress'), max_length=30)),
                ('sw_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.hardware')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
