# Generated by Django 3.2.6 on 2021-08-04 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20210804_1713'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='equipment_type',
            field=models.CharField(choices=[('OBSOLETE', 'obsolete'), ('AVAILABLE', 'Available'), ('UNDER_REPAIR', 'Under repair'), ('SAMPLING', 'Sampling'), ('UNRELIABLE', 'Unreliable')], default='SW', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='hw_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.hardware'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='sw_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tools.software'),
        ),
    ]
