# Generated by Django 3.2.6 on 2021-08-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210804_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='equipment_type',
            field=models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software')], max_length=20),
        ),
    ]
