# Generated by Django 3.2.6 on 2021-10-07 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_reservation_equipment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='sw_equipment',
        ),
    ]
