# Generated by Django 3.2.6 on 2021-08-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Hardware', max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('STATE 1', 'State 1'), ('STATE 2', 'State 2'), ('STATE 3', 'State 3')], max_length=10)),
                ('comptability', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=100)),
                ('drivers', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2500)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Software', max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('STATE 1', 'State 1'), ('STATE 2', 'State 2'), ('STATE 3', 'State 3')], max_length=10)),
                ('qa_reference', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('buy_date', models.DateField()),
                ('details', models.TextField()),
            ],
        ),
    ]
