# Generated by Django 3.2.6 on 2021-08-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HW', 'Hardware'), ('SW', 'Software')], max_length=10)),
                ('version', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('STATE 1', 'State 1'), ('STATE 2', 'State 2'), ('STATE 3', 'State 3')], max_length=10)),
                ('comptability', models.CharField(max_length=50)),
                ('licence', models.CharField(max_length=100)),
                ('drivers', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=2500)),
            ],
        ),
        migrations.AlterField(
            model_name='software',
            name='details',
            field=models.TextField(),
        ),
    ]
