# Generated by Django 3.2.6 on 2021-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='link',
            field=models.CharField(default='http://www.aws.com/aes/bucketa/memo1.doc', max_length=255),
            preserve_default=False,
        ),
    ]
