# Generated by Django 3.2.6 on 2021-08-02 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20210802_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='type',
            field=models.CharField(default='Hardware', max_length=10),
        ),
        migrations.AlterField(
            model_name='software',
            name='type',
            field=models.CharField(default='Software', max_length=10),
        ),
    ]
