# Generated by Django 3.2.6 on 2021-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_document_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.CharField(choices=[('OBSOLETE', 'obsolete'), ('AVAILABLE', 'Available'), ('UNDER_REPAIR', 'Under repair'), ('SAMPLING', 'Sampling'), ('UNRELIABLE', 'Unreliable')], max_length=20),
        ),
        migrations.AlterField(
            model_name='software',
            name='status',
            field=models.CharField(choices=[('OBSOLETE', 'obsolete'), ('AVAILABLE', 'Available'), ('UNDER_REPAIR', 'Under repair'), ('SAMPLING', 'Sampling'), ('UNRELIABLE', 'Unreliable')], max_length=20),
        ),
    ]
