# Generated by Django 3.2.6 on 2021-08-12 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0015_auto_20210804_1713'),
        ('tools', '0004_auto_20210804_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GenericFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_PROOFREADING', 'In proofreading'), ('IN_CORRECTION', 'In correction'), ('PUBLISHED', 'Published')], max_length=50)),
                ('keywords', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('C', 'C'), ('C++', 'C++'), ('C#', 'C#'), ('JAVA', 'Java'), ('RUBY', 'Ruby'), ('GOLANG', 'Golang')], max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
