# Generated by Django 3.2.6 on 2021-10-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20210812_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='link',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
