# Generated by Django 3.2.6 on 2021-10-08 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_hardware_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='link',
            field=models.CharField(default='', max_length=2500, null=True),
        ),
    ]
